service: aws-nodejs-typescript-template

package:
  exclude:
    - src/**/_tests_/**/*

custom:
  customStage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  customEnvironment:
    ENV:
      dev: dev
      staging: staging
      prod: prod

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: ap-south-1
  logRetentionInDays: 7
  timeout: 30
  environment:
    ENV: ${self:custom.customEnvironment.ENV.${self:custom.customStage}}

plugins:
  localPath: ../..
  modules:
    - serverless-webpack
    - serverless-offline

functions:
  hello:
    handler: src/handler.handle
    events:
      - httpApi:
          method: POST
          path: /handle
